language: python
python: "2.7"
install: pip install pyparsing configparser pytest coveralls coverage pytest-cov cpplint
script: PYTHONPATH=eecs183style py.test --cov . regression_test.py
after_success:
    - coveralls
